<?php

return [
    'terms' => [
        'PHP' => ['definition' => 'Linguagem de programação usada principalmente para criar aplicações web no servidor.', 'example' => '<?php echo "Olá";'],
        'HTML' => ['definition' => 'Linguagem de marcação que organiza o conteúdo de uma página web.', 'example' => '<h1>Título</h1>'],
        'CSS' => ['definition' => 'Linguagem que define cores, tamanhos e a aparência dos elementos HTML.', 'example' => 'h1 { color: blue; }'],
        'JavaScript' => ['definition' => 'Linguagem usada para adicionar comportamento e interação às páginas.', 'example' => 'button.addEventListener(...)'],
        'SQL' => ['definition' => 'Linguagem usada para consultar e alterar dados de um banco de dados.', 'example' => 'SELECT * FROM users;'],
        'HTTP' => ['definition' => 'Protocolo usado na comunicação entre o navegador e o servidor.', 'example' => 'GET /aulas'],
        'JSON' => ['definition' => 'Formato de texto usado para trocar dados entre sistemas.', 'example' => '{"nome":"Ana"}'],
        'API' => ['definition' => 'Conjunto de regras e endereços que permite a comunicação entre aplicações.', 'example' => 'GET /api/usuarios'],
        'URL' => ['definition' => 'Endereço completo de um recurso na internet.', 'example' => 'https://site.com/aulas'],
        'CLI' => ['definition' => 'Interface de linha de comando: permite controlar programas digitando comandos no terminal.', 'example' => 'php artisan migrate'],
        'IDE' => ['definition' => 'Programa que reúne editor de código, sugestões, execução e ferramentas de desenvolvimento.', 'example' => 'VS Code ou PhpStorm'],
        'POO' => ['definition' => 'Programação Orientada a Objetos: organiza o código usando classes e objetos.', 'example' => 'class Produto { }'],
        'MVC' => ['definition' => 'Model-View-Controller: separa dados, interface e controle da aplicação.', 'example' => 'Model + View + Controller'],
        'ORM' => ['definition' => 'Mapeamento Objeto-Relacional: permite trabalhar com tabelas usando objetos e métodos.', 'example' => 'User::where(...)'],
        'CRUD' => ['definition' => 'Create, Read, Update e Delete: criar, ler, atualizar e excluir dados.', 'example' => 'Cadastrar, listar, editar e remover'],
        'CSRF' => ['definition' => 'Proteção contra requisições falsas enviadas por outro site em nome do usuário.', 'example' => '@csrf'],
        'XP' => ['definition' => 'Pontos de experiência recebidos ao concluir atividades.', 'example' => '50 XP'],
        'Laravel' => ['definition' => 'Framework PHP que oferece uma estrutura pronta para criar aplicações web.', 'example' => 'php artisan serve'],
        'framework' => ['definition' => 'Conjunto de ferramentas e regras que fornece uma base para desenvolver aplicações.', 'example' => 'Laravel é um framework PHP'],
        'Eloquent' => ['definition' => 'ORM do Laravel usado para consultar o banco por meio de Models.', 'example' => 'User::where("active", true)->get()'],
        'Query Builder' => ['definition' => 'Construtor de consultas do Laravel que monta comandos SQL com métodos PHP.', 'example' => 'DB::table("users")->get()'],
        'Collection' => ['definition' => 'Objeto do Laravel com métodos para filtrar, transformar e organizar conjuntos de dados.', 'example' => '$users->filter(...)'],
        'N+1' => ['definition' => 'Problema de desempenho causado por muitas consultas repetidas ao carregar relacionamentos.', 'example' => 'Use with("posts") para evitar'],
        'eager loading' => ['definition' => 'Carregamento antecipado de relacionamentos para evitar consultas repetidas.', 'example' => 'User::with("posts")->get()'],
        'Model' => ['definition' => 'Classe que representa e manipula dados de uma tabela.', 'example' => 'class User extends Model'],
        'View' => ['definition' => 'Parte responsável por apresentar a interface ao usuário.', 'example' => 'resources/views/aula.blade.php'],
        'Controller' => ['definition' => 'Classe que recebe a requisição e coordena a resposta da aplicação.', 'example' => 'LearningController'],
        'Route' => ['definition' => 'Regra que liga um endereço da aplicação a uma ação.', 'example' => 'Route::get("/aulas", ...)'],
        'Middleware' => ['definition' => 'Camada que verifica ou modifica uma requisição antes de ela chegar ao Controller.', 'example' => 'middleware("auth")'],
        'Request' => ['definition' => 'Objeto que contém os dados enviados pelo navegador ao servidor.', 'example' => '$request->input("nome")'],
        'Response' => ['definition' => 'Resposta enviada pelo servidor ao navegador.', 'example' => 'return response()->json(...)'],
        'migration' => ['definition' => 'Arquivo que cria ou altera a estrutura das tabelas do banco.', 'example' => 'php artisan migrate'],
        'seeder' => ['definition' => 'Classe que insere dados iniciais ou dados de teste no banco.', 'example' => 'DatabaseSeeder'],
        'factory' => ['definition' => 'Fábrica que gera dados falsos para testes e desenvolvimento.', 'example' => 'User::factory()->create()'],
        'Blade' => ['definition' => 'Sistema de templates do Laravel usado para escrever HTML com recursos do PHP.', 'example' => '{{ $usuario->name }}'],
        'Artisan' => ['definition' => 'Ferramenta de linha de comando do Laravel.', 'example' => 'php artisan make:model Produto'],
        'banco de dados' => ['definition' => 'Sistema que armazena informações de forma organizada e persistente.', 'example' => 'PostgreSQL, MySQL ou SQLite'],
        'tabela' => ['definition' => 'Estrutura do banco que organiza dados em linhas e colunas.', 'example' => 'Tabela users'],
        'registro' => ['definition' => 'Uma linha completa de dados dentro de uma tabela.', 'example' => 'Um usuário da tabela users'],
        'chave primária' => ['definition' => 'Coluna que identifica cada registro de forma única.', 'example' => 'id'],
        'chave estrangeira' => ['definition' => 'Coluna que conecta um registro a outra tabela.', 'example' => 'user_id'],
        'relacionamento' => ['definition' => 'Ligação entre Models ou tabelas.', 'example' => 'Um usuário possui muitos posts'],
        'soft delete' => ['definition' => 'Exclusão lógica: o registro continua no banco, mas é marcado como removido.', 'example' => 'deleted_at'],
        'mass assignment' => ['definition' => 'Preenchimento de vários atributos de um Model usando um único array.', 'example' => 'User::create($dados)'],
        'fillable' => ['definition' => 'Lista de atributos que podem ser preenchidos em massa com segurança.', 'example' => 'protected $fillable = ["name"]'],
        'timestamps' => ['definition' => 'Datas automáticas de criação e atualização de um registro.', 'example' => 'created_at e updated_at'],
        'variável' => ['definition' => 'Espaço identificado que guarda um valor que pode mudar.', 'example' => '$nome = "Ana";'],
        'variável PHP' => ['definition' => 'No PHP, toda variável começa com $. O nome identifica onde um valor está guardado.', 'example' => '$idade = 20;'],
        'constante' => ['definition' => 'Nome associado a um valor que não deve mudar durante a execução.', 'example' => 'const TAXA = 10;'],
        'string' => ['definition' => 'Tipo de dado que representa texto.', 'example' => '"Olá, mundo"'],
        'integer' => ['definition' => 'Tipo de dado que representa um número inteiro, sem casas decimais.', 'example' => '42'],
        'int' => ['definition' => 'Forma curta de integer: um número inteiro.', 'example' => 'function dobro(int $n)'],
        'float' => ['definition' => 'Tipo de dado numérico que pode ter casas decimais.', 'example' => '19.90'],
        'boolean' => ['definition' => 'Tipo de dado que possui apenas dois valores: verdadeiro ou falso.', 'example' => 'true ou false'],
        'bool' => ['definition' => 'Forma curta de boolean: verdadeiro ou falso.', 'example' => 'function ativo(): bool'],
        'null' => ['definition' => 'Valor especial que representa ausência de valor.', 'example' => '$nome = null;'],
        'array associativo' => ['definition' => 'Array que usa nomes como chaves em vez de apenas posições numéricas.', 'example' => '["nome" => "Ana"]'],
        'array' => ['definition' => 'Estrutura que armazena vários valores em uma única variável.', 'example' => '[10, 20, 30]'],
        'índice' => ['definition' => 'Posição numérica de um item dentro de um array.', 'example' => '$nomes[0]'],
        'chave' => ['definition' => 'Identificador usado para encontrar um valor em um array associativo.', 'example' => '$usuario["nome"]'],
        'valor' => ['definition' => 'Informação guardada em uma variável, posição ou chave.', 'example' => '$idade = 20'],
        'tipo de dado' => ['definition' => 'Categoria que informa como um valor deve ser interpretado.', 'example' => 'string, int, float ou bool'],
        'operador' => ['definition' => 'Símbolo que realiza uma operação com um ou mais valores.', 'example' => '+, ===, &&'],
        'atribuição' => ['definition' => 'Ação de guardar um valor em uma variável usando o sinal de igual.', 'example' => '$total = 10;'],
        'concatenação' => ['definition' => 'União de textos. No PHP, é feita com um ponto.', 'example' => '"Olá " . $nome'],
        'comparação' => ['definition' => 'Verificação entre valores que produz verdadeiro ou falso.', 'example' => '$idade >= 18'],
        'operador lógico' => ['definition' => 'Operador que combina ou inverte condições.', 'example' => '&&, || e !'],
        'bitwise' => ['definition' => 'Operação que trabalha diretamente com os bits de números inteiros.', 'example' => '$a & $b'],
        'ternário' => ['definition' => 'Forma curta de escolher entre dois valores usando uma condição.', 'example' => '$ok ? "Sim" : "Não"'],
        'null coalescing' => ['definition' => 'Operador que usa um valor alternativo quando o primeiro é null ou não existe.', 'example' => '$nome ?? "Visitante"'],
        'condição' => ['definition' => 'Expressão avaliada como verdadeira ou falsa para decidir o próximo passo.', 'example' => '$idade >= 18'],
        'loop' => ['definition' => 'Estrutura que repete um bloco de código.', 'example' => 'for, while ou foreach'],
        'iteração' => ['definition' => 'Uma execução completa do bloco dentro de um loop.', 'example' => 'A terceira volta do for'],
        'contador' => ['definition' => 'Variável usada para acompanhar quantas repetições já aconteceram.', 'example' => '$i++'],
        'acumulador' => ['definition' => 'Variável que soma ou reúne resultados durante repetições.', 'example' => '$total += $valor'],
        'escopo' => ['definition' => 'Região do código onde uma variável ou função pode ser acessada.', 'example' => 'Escopo local de uma função'],
        'função' => ['definition' => 'Bloco de código reutilizável que realiza uma tarefa.', 'example' => 'function somar($a, $b)'],
        'parâmetro' => ['definition' => 'Nome declarado na função para receber um valor.', 'example' => '$nome em function saudar($nome)'],
        'argumento' => ['definition' => 'Valor real enviado ao chamar uma função.', 'example' => '"Ana" em saudar("Ana")'],
        'retorno' => ['definition' => 'Valor que uma função entrega para quem a chamou.', 'example' => 'return $total;'],
        'classe' => ['definition' => 'Molde que define propriedades e comportamentos de objetos.', 'example' => 'class Produto { }'],
        'objeto' => ['definition' => 'Elemento criado a partir de uma classe.', 'example' => '$produto = new Produto();'],
        'instância' => ['definition' => 'Objeto específico criado a partir de uma classe.', 'example' => 'new Produto()'],
        'propriedade' => ['definition' => 'Variável que pertence a uma classe ou objeto.', 'example' => '$produto->preco'],
        'método' => ['definition' => 'Função que pertence a uma classe.', 'example' => '$produto->calcularTotal()'],
        'construtor' => ['definition' => 'Método executado automaticamente quando um objeto é criado.', 'example' => '__construct()'],
        'herança' => ['definition' => 'Recurso que permite uma classe aproveitar características de outra.', 'example' => 'class Admin extends User'],
        'interface' => ['definition' => 'Contrato que define métodos que uma classe precisa implementar.', 'example' => 'interface Autenticavel'],
        'trait' => ['definition' => 'Bloco de métodos reutilizáveis que pode ser incluído em várias classes.', 'example' => 'use Notificavel;'],
        'namespace' => ['definition' => 'Forma de organizar classes e evitar conflitos de nomes.', 'example' => 'namespace App\\Models;'],
        'exceção' => ['definition' => 'Objeto que representa um erro ou situação inesperada durante a execução.', 'example' => 'throw new Exception(...)'],
        'callback' => ['definition' => 'Função enviada para ser executada por outra função.', 'example' => 'array_map(fn ($n) => $n * 2, $nums)'],
        'closure' => ['definition' => 'Função anônima que pode ser guardada em uma variável ou enviada como argumento.', 'example' => '$dobro = fn ($n) => $n * 2'],
        'função anônima' => ['definition' => 'Função sem nome, normalmente usada como valor ou callback.', 'example' => 'function ($item) { return $item; }'],
        'recursão' => ['definition' => 'Técnica em que uma função chama a si mesma.', 'example' => 'fatorial($n - 1)'],
        'validação' => ['definition' => 'Verificação que confirma se os dados seguem as regras esperadas.', 'example' => 'O e-mail é obrigatório'],
        'sessão' => ['definition' => 'Dados temporários associados a um usuário entre várias requisições.', 'example' => 'session(["nome" => "Ana"])'],
        'cookie' => ['definition' => 'Pequeno dado salvo pelo navegador e enviado ao servidor.', 'example' => 'cookie("tema", "dark")'],
        'autenticação' => ['definition' => 'Processo de confirmar a identidade de um usuário.', 'example' => 'Login com e-mail e senha'],
        'autorização' => ['definition' => 'Verificação do que um usuário autenticado pode fazer.', 'example' => 'Somente administradores podem excluir'],
        'endpoint' => ['definition' => 'Endereço específico de uma API que executa uma operação.', 'example' => 'GET /api/produtos'],
        'status code' => ['definition' => 'Número HTTP que informa o resultado de uma requisição.', 'example' => '200, 404 ou 500'],
        'deploy' => ['definition' => 'Processo de publicar uma aplicação em um servidor.', 'example' => 'Enviar o projeto para o Render'],
        'debug' => ['definition' => 'Processo de investigar o código para encontrar a causa de um problema.', 'example' => 'Analisar valores com var_dump'],
        'sintaxe' => ['definition' => 'Regras que determinam como o código deve ser escrito para a linguagem entendê-lo.', 'example' => 'Cada instrução PHP normalmente termina com ;'],
        'algoritmo' => ['definition' => 'Sequência organizada de passos para resolver um problema.', 'example' => 'Ler, calcular e mostrar o resultado'],
        'echo' => ['definition' => 'Comando do PHP que envia um valor para a saída.', 'example' => 'echo "Olá";'],
        'var_dump' => ['definition' => 'Função que mostra o tipo e o conteúdo detalhado de uma variável.', 'example' => 'var_dump($idade);'],
        'print_r' => ['definition' => 'Função que mostra arrays e objetos de forma legível.', 'example' => 'print_r($usuarios);'],
        'PHP_EOL' => ['definition' => 'End Of Line: constante do PHP que representa uma quebra de linha.', 'example' => 'echo $nome . PHP_EOL;'],
        'count' => ['definition' => 'Função que conta quantos itens existem em um array ou Collection compatível.', 'example' => 'count($nomes);'],
        'array_map' => ['definition' => 'Aplica uma função a cada item de um array e devolve um novo array.', 'example' => 'array_map(fn ($n) => $n * 2, $numeros);'],
        'array_sum' => ['definition' => 'Soma todos os valores numéricos de um array.', 'example' => 'array_sum([10, 20, 30]);'],
        'explode' => ['definition' => 'Divide uma string em partes e devolve um array.', 'example' => 'explode(",", "PHP,Laravel");'],
        'implode' => ['definition' => 'Junta os itens de um array em uma única string.', 'example' => 'implode(", ", $nomes);'],
        'filter_var' => ['definition' => 'Valida ou filtra um valor usando uma regra pronta do PHP.', 'example' => 'filter_var($email, FILTER_VALIDATE_EMAIL);'],
        'htmlspecialchars' => ['definition' => 'Converte caracteres especiais em texto seguro para exibir no HTML.', 'example' => 'htmlspecialchars($nome);'],
        'range' => ['definition' => 'Cria um array com uma sequência de valores.', 'example' => 'range(1, 5);'],
        'str_replace' => ['definition' => 'Procura um trecho em uma string e o substitui por outro.', 'example' => 'str_replace("azul", "verde", $texto);'],
        'strtoupper' => ['definition' => 'Transforma as letras de uma string em maiúsculas.', 'example' => 'strtoupper("php");'],
        'trim' => ['definition' => 'Remove espaços desnecessários do começo e do fim de uma string.', 'example' => 'trim($nome);'],
        'empty' => ['definition' => 'Verifica se um valor está vazio, é zero, false, null ou não existe.', 'example' => 'empty($nome);'],
        'unset' => ['definition' => 'Remove uma variável ou um item de um array.', 'example' => 'unset($usuario["senha"]);'],
        'DateTime' => ['definition' => 'Classe nativa do PHP usada para trabalhar com datas e horários.', 'example' => 'new DateTime("now");'],
        '__construct' => ['definition' => 'Nome especial do método construtor, executado ao criar um objeto.', 'example' => 'public function __construct()'],
        'function' => ['definition' => 'Palavra usada para declarar uma função ou um método no PHP.', 'example' => 'function somar($a, $b) { }'],
        'fn' => ['definition' => 'Forma curta de criar uma função anônima de uma única expressão.', 'example' => 'fn ($n) => $n * 2'],
        'as' => ['definition' => 'No foreach, separa a coleção do valor recebido em cada repetição.', 'example' => 'foreach ($nomes as $nome)'],
        'use' => ['definition' => 'Importa uma classe ou permite que uma closure utilize uma variável externa.', 'example' => 'use App\\Models\\User;'],
        'true' => ['definition' => 'Valor booleano que representa verdadeiro.', 'example' => '$ativo = true;'],
        'false' => ['definition' => 'Valor booleano que representa falso.', 'example' => '$bloqueado = false;'],
        '$this' => ['definition' => 'Variável especial que representa o próprio objeto dentro de seus métodos.', 'example' => '$this->nome'],
        'try' => ['definition' => 'Inicia um bloco de código que pode gerar uma exceção.', 'example' => 'try { executar(); }'],
        'catch' => ['definition' => 'Captura e trata uma exceção produzida dentro do bloco try.', 'example' => 'catch (Exception $erro) { }'],
        'throw' => ['definition' => 'Interrompe o fluxo normal lançando uma exceção.', 'example' => 'throw new Exception("Inválido");'],
        'finally' => ['definition' => 'Bloco executado ao final de try/catch, ocorrendo erro ou não.', 'example' => 'finally { fecharConexao(); }'],
        'abstract' => ['definition' => 'Define uma classe incompleta ou método que deverá ser implementado por uma classe filha.', 'example' => 'abstract class Pagamento'],
        'final' => ['definition' => 'Impede que uma classe seja herdada ou que um método seja sobrescrito.', 'example' => 'final class Configuracao'],
        'readonly' => ['definition' => 'Indica que uma propriedade só pode receber valor uma vez.', 'example' => 'public readonly int $id'],
        'self' => ['definition' => 'Representa a própria classe em um acesso estático.', 'example' => 'self::TAXA'],
        'strlen' => ['definition' => 'Conta quantos bytes existem em uma string.', 'example' => 'strlen("PHP");'],
        'in_array' => ['definition' => 'Verifica se um valor existe dentro de um array.', 'example' => 'in_array("PHP", $cursos);'],
        'json_encode' => ['definition' => 'Converte um valor PHP para texto no formato JSON.', 'example' => 'json_encode($usuario);'],
        'json_decode' => ['definition' => 'Converte um texto JSON em um valor que o PHP consegue usar.', 'example' => 'json_decode($json, true);'],
        'format' => ['definition' => 'Formata uma data usando o padrão informado.', 'example' => '$data->format("d/m/Y");'],
        'modify' => ['definition' => 'Altera uma data usando uma instrução textual.', 'example' => '$data->modify("+1 day");'],
        'diff' => ['definition' => 'Calcula a diferença entre dois objetos de data.', 'example' => '$inicio->diff($fim);'],
        'where' => ['definition' => 'Método que adiciona uma condição a uma consulta no banco.', 'example' => 'User::where("active", true)->get();'],
        'whereIn' => ['definition' => 'Método que filtra uma coluna por uma lista de valores permitidos.', 'example' => 'User::whereIn("id", [1, 2])->get();'],
        'first' => ['definition' => 'Retorna somente o primeiro resultado de uma consulta ou null.', 'example' => 'User::where("email", $email)->first();'],
        'firstOrFail' => ['definition' => 'Retorna o primeiro resultado ou gera um erro 404 quando nada é encontrado.', 'example' => 'User::where("id", $id)->firstOrFail();'],
        'create' => ['definition' => 'Cria e salva um novo registro com os dados informados.', 'example' => 'User::create($dados);'],
        'update' => ['definition' => 'Atualiza dados de um ou mais registros existentes.', 'example' => '$usuario->update($dados);'],
        'delete' => ['definition' => 'Remove um registro do banco de dados.', 'example' => '$usuario->delete();'],
        'updateOrCreate' => ['definition' => 'Atualiza um registro encontrado ou cria um novo quando ele não existe.', 'example' => 'User::updateOrCreate(["email" => $email], $dados);'],
        'for' => ['definition' => 'Loop indicado quando você sabe como iniciar, quando parar e como avançar.', 'example' => 'for ($i = 1; $i <= 5; $i++)'],
        'foreach' => ['definition' => 'Loop usado para percorrer os itens de um array ou Collection.', 'example' => 'foreach ($nomes as $nome)'],
        'while' => ['definition' => 'Loop que continua enquanto uma condição for verdadeira.', 'example' => 'while ($saldo > 0)'],
        'do...while' => ['definition' => 'Loop que executa o bloco ao menos uma vez e depois verifica a condição.', 'example' => 'do { ... } while ($ok);'],
        'if' => ['definition' => 'Estrutura que executa um bloco somente se uma condição for verdadeira.', 'example' => 'if ($idade >= 18)'],
        'else' => ['definition' => 'Bloco executado quando a condição do if é falsa.', 'example' => 'else { echo "Menor"; }'],
        'elseif' => ['definition' => 'Permite testar outra condição quando o if anterior foi falso.', 'example' => 'elseif ($nota >= 7)'],
        'switch' => ['definition' => 'Estrutura que escolhe um bloco comparando um valor com vários casos.', 'example' => 'switch ($opcao)'],
        'match' => ['definition' => 'Expressão do PHP que compara um valor e retorna o resultado correspondente.', 'example' => 'match ($status) { 1 => "Ativo" }'],
        'break' => ['definition' => 'Interrompe imediatamente um loop ou switch.', 'example' => 'if ($achou) break;'],
        'continue' => ['definition' => 'Pula o restante da iteração atual e segue para a próxima.', 'example' => 'if ($n < 0) continue;'],
        'return' => ['definition' => 'Encerra uma função e pode devolver um valor.', 'example' => 'return $resultado;'],
        'new' => ['definition' => 'Palavra usada para criar um novo objeto a partir de uma classe.', 'example' => 'new Produto()'],
        'extends' => ['definition' => 'Indica que uma classe herda de outra.', 'example' => 'class Admin extends User'],
        'implements' => ['definition' => 'Indica que uma classe segue o contrato de uma interface.', 'example' => 'class User implements Autenticavel'],
        'public' => ['definition' => 'Permite acessar uma propriedade ou método de qualquer lugar.', 'example' => 'public function salvar()'],
        'private' => ['definition' => 'Permite acesso somente dentro da própria classe.', 'example' => 'private string $senha'],
        'protected' => ['definition' => 'Permite acesso na classe e em suas classes filhas.', 'example' => 'protected int $id'],
        'static' => ['definition' => 'Indica que um membro pertence à classe, sem exigir um objeto criado.', 'example' => 'User::find(1)'],
        '<?php' => ['definition' => 'Tag que informa ao servidor onde começa um bloco de código PHP.', 'example' => '<?php echo "Olá";'],
        '->' => ['definition' => 'Operador usado para acessar uma propriedade ou método de um objeto.', 'example' => '$usuario->nome'],
        '::' => ['definition' => 'Operador usado para acessar membros estáticos de uma classe.', 'example' => 'User::find(1)'],
        '=>' => ['definition' => 'Associa uma chave a um valor em arrays e também aparece em funções arrow.', 'example' => '["nome" => "Ana"]'],
        '===' => ['definition' => 'Compara valor e tipo. Só é verdadeiro quando ambos são iguais.', 'example' => '$idade === 18'],
        '!==' => ['definition' => 'Verifica se o valor ou o tipo são diferentes.', 'example' => '$status !== "ativo"'],
        '==' => ['definition' => 'Compara valores permitindo conversão de tipos.', 'example' => '"5" == 5'],
        '!=' => ['definition' => 'Verifica se dois valores são diferentes.', 'example' => '$a != $b'],
        '<=' => ['definition' => 'Menor ou igual.', 'example' => '$i <= 10'],
        '>=' => ['definition' => 'Maior ou igual.', 'example' => '$idade >= 18'],
        '&&' => ['definition' => 'E lógico: todas as condições precisam ser verdadeiras.', 'example' => '$idade >= 18 && $ativo'],
        '||' => ['definition' => 'OU lógico: basta uma das condições ser verdadeira.', 'example' => '$admin || $editor'],
        '??' => ['definition' => 'Usa o valor da direita quando o valor da esquerda é null ou não existe.', 'example' => '$nome ?? "Visitante"'],
        '?:' => ['definition' => 'Operador ternário abreviado ou representação da escolha condição ? valor : alternativa.', 'example' => '$nome ?: "Sem nome"'],
        '++' => ['definition' => 'Incremento: soma 1 ao valor da variável.', 'example' => '$i++'],
        '--' => ['definition' => 'Decremento: subtrai 1 do valor da variável.', 'example' => '$i--'],
        '.=' => ['definition' => 'Concatena um texto ao conteúdo atual da variável.', 'example' => '$texto .= "!"'],
        '+=' => ['definition' => 'Soma um valor e guarda o novo resultado na mesma variável.', 'example' => '$total += 10'],
    ],
];
